apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chirpstack.fullname" . }}
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
data:
  chirpstack.toml: |
    [logging]
    level="info"

    [postgresql]
    dsn="postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB?sslmode=disable"

    [redis]
    servers=["redis://$REDIS_HOST/0"]

    [network]
    net_id="{{ .Values.chirpstack.netID }}"
    enabled_regions=["{{ .Values.chirpstack.region }}"]

    [api]
    bind="0.0.0.0:8080"
    secret="$CHIRPSTACK_SECRET"

    [integration]
    enabled=["mqtt"]

    [integration.mqtt]
    server="tcp://$MQTT_BROKER_HOST:1883/"
    json=true
