{{- if .Values.basicStationGatewayBridge.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chirpstack.fullname" . }}-basic-station
  labels:
    app: basic-station
data:
  chirpstack-basic-station.toml: |
    [general]
    log_level=4

    [backend]
    type="basic_station"

    [backend.basic_station]
    bind="0.0.0.0:{{ .Values.basicStationGatewayBridge.port }}"
    # if TLS terminated at the pod itself
    # cloudflared will terminate TLS, so we don't need it
    # ca_cert=""
    {{- if .Values.basicStationGatewayBridge.internal_tls }}
    tls_cert="/etc/chirpstack-basic-station-tls/tls.crt"
    tls_key="/etc/chirpstack-basic-station-tls/tls.key"
    {{- end }}

    region="US915"

    frequency_min=902000000
    frequency_max=928000000

    [[backend.basic_station.concentrators]]

    [backend.basic_station.concentrators.multi_sf]
      frequencies=[
        903900000,
        904100000,
        904300000,
        904500000,
        904700000,
        904900000,
        905100000,
        905300000,
      ]

    [backend.basic_station.concentrators.lora_std]
      frequency=904600000
      bandwidth=500000
      spreading_factor=8

    [integration]
    marshaler="json"

    [integration.mqtt]
    event_topic_template="{{ .Values.chirpstack.region }}/gateway/{{ "{{ .GatewayID }}" }}/event/{{ "{{ .EventType }}" }}"
    state_topic_template="{{ .Values.chirpstack.region }}/gateway/{{ "{{ .GatewayID }}" }}/state/{{ "{{ .StateType }}" }}"
    command_topic_template="{{ .Values.chirpstack.region }}/gateway/{{ "{{ .GatewayID }}" }}/command/#"

    [integration.mqtt.auth]
    type="generic"
    [integration.mqtt.auth.generic]
    servers=["tcp://{{.Release.Name}}-{{ .Values.mosquitto.host }}:{{ .Values.mosquitto.port }}/"]
{{- end }}
