apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chirpstack.fullname" . }}-mosquitto
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
