apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-chirp-redis
  labels:
    app: chirp-cache
    release: {{ .Release.Name }}
    component: redis

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chirp-cache
  template:
    metadata:
      labels:
        app: chirp-cache
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          args: ["--save", "60", "1", "--appendonly", "yes"]
          ports:
            - containerPort: {{ .Values.redis.port }}
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-{{ .Values.redis.host }}
  labels:
    app: chirp-cache
spec:
  selector:
    app: chirp-cache
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
