apiVersion: v1
kind: Secret
metadata:
  name: chirp-secrets
  namespace: chirp
type: Opaque
stringData:
  POSTGRES_DB: "..."
  POSTGRES_USER: "..."
  POSTGRES_PASSWORD: "..."
  CHIRPSTACK_SECRET: "..."
